### ISSUE TITLE
The docker image seems not the good one

### ISSUE THREAD

**Issue by ClaudeCoulombe** [wagonhelm/TF_ObjectDetection_API#1]
It seems that the docker image on GitHub is related to the «object_detection_tutorial.ipynb» tutorial , not the «ChessObjectDetection.ipynb» tutorial published by O'Reilly last week.

**Comment by ClaudeCoulombe** [comment]
I'll try it as you suggested. 
Thanks!
Claude

**Comment by wagonhelm** [comment]
I had no issues with the docker file at time of testing, is everything good?  If so please close.

**Comment by ClaudeCoulombe** [comment]
Greetings, I've checked, you're right, I've probably mixed-up docker images on my laptop. I am indeed sorry that have bothered you.
